version: "3.0.0"
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: "socialy-db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - socialy-db-vol:/var/lib/mysql

volumes:
  socialy-db-vol:
